# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('area', models.CharField(default='DEFAULT VALUE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='aimodels',
            name='dategen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aimodels',
            name='predictors',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='aimodels',
            name='problemtoapply',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='aimodels',
            name='target',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='aimodels',
            name='method',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='aimodels',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
